<?php

declare(strict_types=1);

namespace FppTest;

use Fpp\Constructor;
use Fpp\Definition;
use Fpp\DefinitionCollection;
use Fpp\Deriving\FromString;
use Fpp\Deriving\ToString;
use PHPUnit\Framework\TestCase;
use const Fpp\loadTemplate;
use const Fpp\replace;
use function Fpp\dump;

class DumpTest extends TestCase
{
    /**
     * @var callable
     */
    private $dump;

    protected function setUp(): void
    {
        $this->dump = function (DefinitionCollection $collection): string {
            return dump($collection, loadTemplate, replace);
        };
    }

    /**
     * @test
     */
    public function it_dumps_string_class(): void
    {
        $dump = $this->dump;

        $definition = new Definition('Foo', 'Bar', [new Constructor('String')]);
        $collection = $this->buildCollection($definition);

        $expected = <<<CODE
<?php
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Foo {
    class Bar
    {
        private \$value;

        public function __construct(string \$value)
        {
            \$this->value = \$value;
        }

        public function value(): string
        {
            return \$this->value;
        }
    }
}

CODE;

        $this->assertSame($expected, $dump($collection));
    }

    /**
     * @test
     */
    public function it_dumps_string_class_deriving_from_and_to_string(): void
    {
        $dump = $this->dump;

        $definition = new Definition('Foo', 'Bar', [new Constructor('String')], [new FromString(), new ToString()]);
        $collection = $this->buildCollection($definition);

        $expected = <<<CODE
<?php
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Foo {
    class Bar
    {
        private \$value;

        public function __construct(string \$value)
        {
            \$this->value = \$value;
        }

        public function value(): string
        {
            return \$this->value;
        }

        public static function fromString(string \$bar): Bar
        {
            return new Bar(\$bar);
        }

        public function toString(): string
        {
            return \$this->value;
        }

        public function __toString(): string
        {
            return \$this->value;
        }
    }
}

CODE;

        $this->assertSame($expected, $dump($collection));
    }

    private function buildCollection(Definition ...$definition): DefinitionCollection
    {
        $collection = new DefinitionCollection();

        foreach (func_get_args() as $arg) {
            $collection->addDefinition($arg);
        }

        return $collection;
    }
}
